version: '3.8'

services:
  postgres:
     container_name: nest-fundamentals-postgres
     image: postgres
     ports:
       - 5432:5432
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: docker
       POSTGRES_DB: nest-fundamentals
       PGDATA: /data/postgres
     volumes:
      - ./data/pg:/data/postgres
  

  cache:
    container_name: nest-fundamentals-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data